-- Shopify auth + webhook delivery (H2 / MySQL-compatible)
CREATE TABLE IF NOT EXISTS shopify_store_auth (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name       VARCHAR(128)  NOT NULL,
    shop_domain     VARCHAR(255)  NOT NULL,
    access_token    VARCHAR(512)  NOT NULL,
    scope           VARCHAR(1024),
    status          VARCHAR(32)   NOT NULL,
    authorized_at   TIMESTAMP,
    updated_at      TIMESTAMP,
    del_flag        INT           NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_shopify_store_auth_domain ON shopify_store_auth (shop_domain);

CREATE TABLE IF NOT EXISTS shopify_webhook_delivery (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    webhook_id      VARCHAR(128)  NOT NULL,
    shop_domain     VARCHAR(255),
    topic           VARCHAR(128),
    created_at      TIMESTAMP     NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_shopify_webhook_delivery_id ON shopify_webhook_delivery (webhook_id);
