-- Portable DDL (H2 / PostgreSQL). Identity via SQL-standard GENERATED BY DEFAULT AS IDENTITY.
-- Shopify auth + webhook delivery
CREATE TABLE IF NOT EXISTS shopify_store_auth (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name       VARCHAR(128)  NOT NULL,
    shop_domain     VARCHAR(255)  NOT NULL,
    access_token    TEXT          NOT NULL,
    scope           TEXT,
    status          VARCHAR(32)   NOT NULL,
    authorized_at   TIMESTAMP,
    updated_at      TIMESTAMP,
    del_flag        INT           NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_shopify_store_auth_domain ON shopify_store_auth (shop_domain);

-- Migration: widen auth token/scope columns for long Shopify grants (idempotent, safe on every boot).
-- Older deployments created these as VARCHAR(512)/VARCHAR(1024); TEXT avoids "value too long" on re-auth.
ALTER TABLE shopify_store_auth ALTER COLUMN access_token SET DATA TYPE TEXT;
ALTER TABLE shopify_store_auth ALTER COLUMN scope SET DATA TYPE TEXT;

CREATE TABLE IF NOT EXISTS shopify_webhook_delivery (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    webhook_id      VARCHAR(128)  NOT NULL,
    shop_domain     VARCHAR(255),
    topic           VARCHAR(128),
    created_at      TIMESTAMP     NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_shopify_webhook_delivery_id ON shopify_webhook_delivery (webhook_id);

-- Standardized product mirror (SPU)
CREATE TABLE IF NOT EXISTS third_platform_product (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name               VARCHAR(128)  NOT NULL,
    shop_type               VARCHAR(32)   NOT NULL,
    third_platform_item_id  VARCHAR(255)  NOT NULL,
    handle                  VARCHAR(255),
    title                   VARCHAR(1024),
    description             TEXT,
    status                  VARCHAR(32),
    currency                VARCHAR(16),
    min_price               DECIMAL(18, 4),
    max_price               DECIMAL(18, 4),
    min_price_local         DECIMAL(18, 4),
    max_price_local         DECIMAL(18, 4),
    min_weight_grams        DOUBLE PRECISION,
    max_weight_grams        DOUBLE PRECISION,
    primary_image_url       VARCHAR(2048),
    updated_at              TIMESTAMP,
    del_flag                INT           NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_tpp_shop_item
    ON third_platform_product (shop_name, third_platform_item_id);

-- Standardized SKU mirror
CREATE TABLE IF NOT EXISTS third_platform_sku (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                VARCHAR(128)  NOT NULL,
    shop_type                VARCHAR(32)   NOT NULL,
    third_platform_item_id   VARCHAR(255)  NOT NULL,
    third_platform_sku_id    VARCHAR(255)  NOT NULL,
    sku                      VARCHAR(255),
    title                    VARCHAR(1024),
    price                    DECIMAL(18, 4),
    price_local              DECIMAL(18, 4),
    weight_grams             DOUBLE PRECISION,
    option1                  VARCHAR(512),
    option2                  VARCHAR(512),
    option3                  VARCHAR(512),
    image_url                VARCHAR(2048),
    barcode                  VARCHAR(255),
    inventory_quantity       INT,
    position                 INT,
    del_flag                 INT           NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_tps_shop_sku
    ON third_platform_sku (shop_name, third_platform_sku_id);

-- Minimal product media mirror
CREATE TABLE IF NOT EXISTS third_platform_product_media (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                VARCHAR(128)  NOT NULL,
    shop_type                VARCHAR(32)   NOT NULL,
    third_platform_item_id   VARCHAR(255)  NOT NULL,
    media_id                 VARCHAR(255)  NOT NULL,
    url                      VARCHAR(2048),
    alt                      VARCHAR(1024),
    position                 INT,
    del_flag                 INT           NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_tppm_shop_media
    ON third_platform_product_media (shop_name, media_id);

-- Platform SKU ↔ Tangbuy candidate matches (SKU-level only; Tangbuy ids are opaque external refs)
CREATE TABLE IF NOT EXISTS shop_product_match_candidate (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                VARCHAR(128)  NOT NULL,
    shop_type                VARCHAR(32)   NOT NULL,
    third_platform_item_id   VARCHAR(255)  NOT NULL,
    third_platform_sku_id    VARCHAR(255)  NOT NULL,
    tangbuy_product_id       VARCHAR(128),
    tangbuy_sku_id           VARCHAR(128)  NOT NULL,
    match_source             VARCHAR(32)   NOT NULL,
    match_score              DECIMAL(6, 4),
    match_reason             VARCHAR(1024),
    status                   VARCHAR(32)   NOT NULL,
    del_flag                 INT           NOT NULL DEFAULT 0,
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_spmc_shop_sku_target
    ON shop_product_match_candidate (shop_name, third_platform_sku_id, tangbuy_sku_id, match_source);

-- Confirmed SKU-level bindings; at most one ACTIVE per (shop_name, third_platform_sku_id)
CREATE TABLE IF NOT EXISTS shop_product_binding (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                VARCHAR(128)  NOT NULL,
    shop_type                VARCHAR(32)   NOT NULL,
    third_platform_item_id   VARCHAR(255),
    third_platform_sku_id    VARCHAR(255)  NOT NULL,
    tangbuy_product_id       VARCHAR(128),
    tangbuy_sku_id           VARCHAR(128),
    bind_source              VARCHAR(32)   NOT NULL,
    candidate_id             BIGINT,
    bind_status              VARCHAR(32)   NOT NULL,
    del_flag                 INT           NOT NULL DEFAULT 0,
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_spb_shop_sku
    ON shop_product_binding (shop_name, third_platform_sku_id);

-- Minimal order header persistence (idempotent by shop_type + shop_name + outer_order_id)
CREATE TABLE IF NOT EXISTS third_platform_order (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                VARCHAR(128)  NOT NULL,
    shop_type                VARCHAR(32)   NOT NULL,
    outer_order_id           VARCHAR(255)  NOT NULL,
    order_name               VARCHAR(255),
    financial_status         VARCHAR(64),
    fulfillment_status       VARCHAR(64),
    currency                 VARCHAR(16),
    total_price              DECIMAL(18, 4),
    platform_created_at      TIMESTAMP,
    platform_updated_at      TIMESTAMP,
    del_flag                 INT           NOT NULL DEFAULT 0,
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_tpo_shop_order
    ON third_platform_order (shop_type, shop_name, outer_order_id);
CREATE INDEX IF NOT EXISTS idx_tpo_shop
    ON third_platform_order (shop_name, del_flag);

-- Order line persistence with binding snapshot
CREATE TABLE IF NOT EXISTS third_platform_order_line (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                VARCHAR(128)  NOT NULL,
    shop_type                VARCHAR(32)   NOT NULL,
    outer_order_id           VARCHAR(255)  NOT NULL,
    line_id                  VARCHAR(255)  NOT NULL,
    outer_variant_id         VARCHAR(255),
    sku                      VARCHAR(255),
    title                    VARCHAR(1024),
    quantity                 INT,
    price                    DECIMAL(18, 4),
    tangbuy_product_id       VARCHAR(128),
    tangbuy_sku_id           VARCHAR(128),
    binding_status           VARCHAR(32)   NOT NULL,
    handling_status          VARCHAR(32),
    handling_note            VARCHAR(512),
    handled_at               TIMESTAMP,
    draft_order_id           BIGINT,
    del_flag                 INT           NOT NULL DEFAULT 0,
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_tpol_shop_line
    ON third_platform_order_line (shop_name, line_id);
CREATE INDEX IF NOT EXISTS idx_tpol_shop_order
    ON third_platform_order_line (shop_name, outer_order_id);
CREATE INDEX IF NOT EXISTS idx_tpol_shop_status
    ON third_platform_order_line (shop_name, binding_status);
CREATE INDEX IF NOT EXISTS idx_tpol_shop_binding_handling
    ON third_platform_order_line (shop_name, binding_status, handling_status);

-- Procurement task outbox (handoff record generated from BOUND order lines)
CREATE TABLE IF NOT EXISTS third_platform_procurement_task (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                VARCHAR(128)  NOT NULL,
    shop_type                VARCHAR(32)   NOT NULL,
    outer_order_id           VARCHAR(255)  NOT NULL,
    line_id                  VARCHAR(255)  NOT NULL,
    tangbuy_product_id       VARCHAR(128),
    tangbuy_sku_id           VARCHAR(128)  NOT NULL,
    quantity                 INT,
    currency                 VARCHAR(16),
    unit_price               DECIMAL(18, 4),
    task_status              VARCHAR(32)   NOT NULL,
    delivery_status          VARCHAR(32)   NOT NULL DEFAULT 'PENDING_DELIVERY',
    delivered_at             TIMESTAMP,
    delivery_attempts        INT           NOT NULL DEFAULT 0,
    last_pulled_at           TIMESTAMP,
    del_flag                 INT           NOT NULL DEFAULT 0,
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_tppt_shop_line
    ON third_platform_procurement_task (shop_name, line_id);
CREATE INDEX IF NOT EXISTS idx_tppt_shop_status
    ON third_platform_procurement_task (shop_name, task_status);
CREATE INDEX IF NOT EXISTS idx_tppt_shop_order
    ON third_platform_procurement_task (shop_name, outer_order_id);
CREATE INDEX IF NOT EXISTS idx_tppt_shop_delivery
    ON third_platform_procurement_task (shop_name, task_status, delivery_status);

-- Consumer integration receipts (main platform / procurement system consuming the outbox).
-- Consumer-side ledger only; delivery fact stays on third_platform_procurement_task.delivery_status.
CREATE TABLE IF NOT EXISTS third_platform_procurement_consumption (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                VARCHAR(128)  NOT NULL,
    task_id                  BIGINT        NOT NULL,
    line_id                  VARCHAR(255),
    consumer_id              VARCHAR(128)  NOT NULL,
    consumer_ref             VARCHAR(256),
    consumption_status       VARCHAR(32)   NOT NULL DEFAULT 'RECEIVED',
    received_at              TIMESTAMP,
    accepted_at              TIMESTAMP,
    del_flag                 INT           NOT NULL DEFAULT 0,
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_tppc_task_consumer
    ON third_platform_procurement_consumption (task_id, consumer_id);
CREATE INDEX IF NOT EXISTS idx_tppc_shop_status
    ON third_platform_procurement_consumption (shop_name, consumption_status);
CREATE INDEX IF NOT EXISTS idx_tppc_task
    ON third_platform_procurement_consumption (task_id);

-- Execution placeholder (stub) for accepted tasks. NOT a real procurement order.
-- execution_status is a new downstream dimension, orthogonal to task/delivery/consumption status.
CREATE TABLE IF NOT EXISTS third_platform_procurement_execution (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                VARCHAR(128)  NOT NULL,
    task_id                  BIGINT        NOT NULL,
    line_id                  VARCHAR(255),
    consumer_id              VARCHAR(128),
    execution_status         VARCHAR(32)   NOT NULL DEFAULT 'PENDING_EXECUTION',
    note                     VARCHAR(512),
    created_at               TIMESTAMP,
    completed_at             TIMESTAMP,
    del_flag                 INT           NOT NULL DEFAULT 0,
    updated_at               TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_tppe_task
    ON third_platform_procurement_execution (task_id);
CREATE INDEX IF NOT EXISTS idx_tppe_shop_status
    ON third_platform_procurement_execution (shop_name, execution_status);

-- Per-shop pricing template (single active row per shop). Deterministic sale-price rule for
-- catalog recommendations: converted = price * exchange_rate; sale = converted * multiplier + addend,
-- then rounding_strategy(decimals). exchange_rate = target units per 1 source unit. Manual/static
-- rate in this phase (no live FX). Template params only; money math is done in BigDecimal in the app.
CREATE TABLE IF NOT EXISTS pricing_template (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                VARCHAR(255)  NOT NULL,
    source_currency          VARCHAR(8)    NOT NULL DEFAULT 'CNY',
    target_currency          VARCHAR(8)    NOT NULL DEFAULT 'USD',
    exchange_rate            DOUBLE PRECISION NOT NULL,
    multiplier               DOUBLE PRECISION NOT NULL DEFAULT 2.0,
    addend                   DOUBLE PRECISION NOT NULL DEFAULT 0,
    rounding_strategy        VARCHAR(16)   NOT NULL DEFAULT 'HALF_UP',
    decimals                 INT           NOT NULL DEFAULT 2,
    del_flag                 INT           NOT NULL DEFAULT 0,
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_pricing_template_shop
    ON pricing_template (shop_name, del_flag);
