-- Portable DDL (H2 / PostgreSQL). Identity via SQL-standard GENERATED BY DEFAULT AS IDENTITY.
-- Shopify auth + webhook delivery
CREATE TABLE IF NOT EXISTS shopify_store_auth (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name       VARCHAR(128)  NOT NULL,
    shop_domain     VARCHAR(255)  NOT NULL,
    access_token    TEXT          NOT NULL,
    scope           TEXT,
    status          VARCHAR(32)   NOT NULL,
    authorized_at   TIMESTAMP,
    updated_at      TIMESTAMP,
    del_flag        INT           NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_shopify_store_auth_domain ON shopify_store_auth (shop_domain);

-- Migration: widen auth token/scope columns for long Shopify grants (idempotent, safe on every boot).
-- Older deployments created these as VARCHAR(512)/VARCHAR(1024); TEXT avoids "value too long" on re-auth.
ALTER TABLE shopify_store_auth ALTER COLUMN access_token SET DATA TYPE TEXT;
ALTER TABLE shopify_store_auth ALTER COLUMN scope SET DATA TYPE TEXT;

CREATE TABLE IF NOT EXISTS shopify_webhook_delivery (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    webhook_id      VARCHAR(128)  NOT NULL,
    shop_domain     VARCHAR(255),
    topic           VARCHAR(128),
    created_at      TIMESTAMP     NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_shopify_webhook_delivery_id ON shopify_webhook_delivery (webhook_id);

-- Standardized product mirror (SPU)
CREATE TABLE IF NOT EXISTS third_platform_product (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name               VARCHAR(128)  NOT NULL,
    shop_type               VARCHAR(32)   NOT NULL,
    third_platform_item_id  VARCHAR(255)  NOT NULL,
    handle                  VARCHAR(255),
    title                   VARCHAR(1024),
    description             TEXT,
    status                  VARCHAR(32),
    currency                VARCHAR(16),
    min_price               DECIMAL(18, 4),
    max_price               DECIMAL(18, 4),
    min_price_local         DECIMAL(18, 4),
    max_price_local         DECIMAL(18, 4),
    min_weight_grams        DOUBLE PRECISION,
    max_weight_grams        DOUBLE PRECISION,
    primary_image_url       VARCHAR(2048),
    updated_at              TIMESTAMP,
    del_flag                INT           NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_tpp_shop_item
    ON third_platform_product (shop_name, third_platform_item_id);

-- Standardized SKU mirror
CREATE TABLE IF NOT EXISTS third_platform_sku (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                VARCHAR(128)  NOT NULL,
    shop_type                VARCHAR(32)   NOT NULL,
    third_platform_item_id   VARCHAR(255)  NOT NULL,
    third_platform_sku_id    VARCHAR(255)  NOT NULL,
    sku                      VARCHAR(255),
    title                    VARCHAR(1024),
    price                    DECIMAL(18, 4),
    price_local              DECIMAL(18, 4),
    weight_grams             DOUBLE PRECISION,
    option1                  VARCHAR(512),
    option2                  VARCHAR(512),
    option3                  VARCHAR(512),
    image_url                VARCHAR(2048),
    barcode                  VARCHAR(255),
    inventory_quantity       INT,
    position                 INT,
    del_flag                 INT           NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_tps_shop_sku
    ON third_platform_sku (shop_name, third_platform_sku_id);

-- Minimal product media mirror
CREATE TABLE IF NOT EXISTS third_platform_product_media (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                VARCHAR(128)  NOT NULL,
    shop_type                VARCHAR(32)   NOT NULL,
    third_platform_item_id   VARCHAR(255)  NOT NULL,
    media_id                 VARCHAR(255)  NOT NULL,
    url                      VARCHAR(2048),
    alt                      VARCHAR(1024),
    position                 INT,
    del_flag                 INT           NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_tppm_shop_media
    ON third_platform_product_media (shop_name, media_id);

-- Platform SKU ↔ Tangbuy candidate matches (SKU-level only; Tangbuy ids are opaque external refs)
CREATE TABLE IF NOT EXISTS shop_product_match_candidate (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                VARCHAR(128)  NOT NULL,
    shop_type                VARCHAR(32)   NOT NULL,
    third_platform_item_id   VARCHAR(255)  NOT NULL,
    third_platform_sku_id    VARCHAR(255)  NOT NULL,
    tangbuy_product_id       VARCHAR(128),
    tangbuy_sku_id           VARCHAR(128)  NOT NULL,
    match_source             VARCHAR(32)   NOT NULL,
    match_score              DECIMAL(6, 4),
    match_reason             VARCHAR(1024),
    status                   VARCHAR(32)   NOT NULL,
    del_flag                 INT           NOT NULL DEFAULT 0,
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_spmc_shop_sku_target
    ON shop_product_match_candidate (shop_name, third_platform_sku_id, tangbuy_sku_id, match_source);

-- Confirmed SKU-level bindings; at most one ACTIVE per (shop_name, third_platform_sku_id)
CREATE TABLE IF NOT EXISTS shop_product_binding (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                VARCHAR(128)  NOT NULL,
    shop_type                VARCHAR(32)   NOT NULL,
    third_platform_item_id   VARCHAR(255),
    third_platform_sku_id    VARCHAR(255)  NOT NULL,
    tangbuy_product_id       VARCHAR(128),
    tangbuy_sku_id           VARCHAR(128),
    bind_source              VARCHAR(32)   NOT NULL,
    candidate_id             BIGINT,
    bind_status              VARCHAR(32)   NOT NULL,
    del_flag                 INT           NOT NULL DEFAULT 0,
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_spb_shop_sku
    ON shop_product_binding (shop_name, third_platform_sku_id);

-- Minimal order header persistence (idempotent by shop_type + shop_name + outer_order_id)
CREATE TABLE IF NOT EXISTS third_platform_order (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                VARCHAR(128)  NOT NULL,
    shop_type                VARCHAR(32)   NOT NULL,
    outer_order_id           VARCHAR(255)  NOT NULL,
    order_name               VARCHAR(255),
    financial_status         VARCHAR(64),
    fulfillment_status       VARCHAR(64),
    currency                 VARCHAR(16),
    total_price              DECIMAL(18, 4),
    platform_created_at      TIMESTAMP,
    platform_updated_at      TIMESTAMP,
    del_flag                 INT           NOT NULL DEFAULT 0,
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_tpo_shop_order
    ON third_platform_order (shop_type, shop_name, outer_order_id);
CREATE INDEX IF NOT EXISTS idx_tpo_shop
    ON third_platform_order (shop_name, del_flag);

-- Order line persistence with binding snapshot
CREATE TABLE IF NOT EXISTS third_platform_order_line (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                VARCHAR(128)  NOT NULL,
    shop_type                VARCHAR(32)   NOT NULL,
    outer_order_id           VARCHAR(255)  NOT NULL,
    line_id                  VARCHAR(255)  NOT NULL,
    outer_variant_id         VARCHAR(255),
    sku                      VARCHAR(255),
    title                    VARCHAR(1024),
    quantity                 INT,
    price                    DECIMAL(18, 4),
    tangbuy_product_id       VARCHAR(128),
    tangbuy_sku_id           VARCHAR(128),
    binding_status           VARCHAR(32)   NOT NULL,
    handling_status          VARCHAR(32),
    handling_note            VARCHAR(512),
    handled_at               TIMESTAMP,
    draft_order_id           BIGINT,
    del_flag                 INT           NOT NULL DEFAULT 0,
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_tpol_shop_line
    ON third_platform_order_line (shop_name, line_id);
CREATE INDEX IF NOT EXISTS idx_tpol_shop_order
    ON third_platform_order_line (shop_name, outer_order_id);
CREATE INDEX IF NOT EXISTS idx_tpol_shop_status
    ON third_platform_order_line (shop_name, binding_status);
CREATE INDEX IF NOT EXISTS idx_tpol_shop_binding_handling
    ON third_platform_order_line (shop_name, binding_status, handling_status);

-- Procurement task outbox (handoff record generated from BOUND order lines)
CREATE TABLE IF NOT EXISTS third_platform_procurement_task (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                VARCHAR(128)  NOT NULL,
    shop_type                VARCHAR(32)   NOT NULL,
    outer_order_id           VARCHAR(255)  NOT NULL,
    line_id                  VARCHAR(255)  NOT NULL,
    tangbuy_product_id       VARCHAR(128),
    tangbuy_sku_id           VARCHAR(128)  NOT NULL,
    quantity                 INT,
    currency                 VARCHAR(16),
    unit_price               DECIMAL(18, 4),
    task_status              VARCHAR(32)   NOT NULL,
    delivery_status          VARCHAR(32)   NOT NULL DEFAULT 'PENDING_DELIVERY',
    delivered_at             TIMESTAMP,
    delivery_attempts        INT           NOT NULL DEFAULT 0,
    last_pulled_at           TIMESTAMP,
    del_flag                 INT           NOT NULL DEFAULT 0,
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_tppt_shop_line
    ON third_platform_procurement_task (shop_name, line_id);
CREATE INDEX IF NOT EXISTS idx_tppt_shop_status
    ON third_platform_procurement_task (shop_name, task_status);
CREATE INDEX IF NOT EXISTS idx_tppt_shop_order
    ON third_platform_procurement_task (shop_name, outer_order_id);
CREATE INDEX IF NOT EXISTS idx_tppt_shop_delivery
    ON third_platform_procurement_task (shop_name, task_status, delivery_status);

-- Consumer integration receipts (main platform / procurement system consuming the outbox).
-- Consumer-side ledger only; delivery fact stays on third_platform_procurement_task.delivery_status.
CREATE TABLE IF NOT EXISTS third_platform_procurement_consumption (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                VARCHAR(128)  NOT NULL,
    task_id                  BIGINT        NOT NULL,
    line_id                  VARCHAR(255),
    consumer_id              VARCHAR(128)  NOT NULL,
    consumer_ref             VARCHAR(256),
    consumption_status       VARCHAR(32)   NOT NULL DEFAULT 'RECEIVED',
    received_at              TIMESTAMP,
    accepted_at              TIMESTAMP,
    del_flag                 INT           NOT NULL DEFAULT 0,
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_tppc_task_consumer
    ON third_platform_procurement_consumption (task_id, consumer_id);
CREATE INDEX IF NOT EXISTS idx_tppc_shop_status
    ON third_platform_procurement_consumption (shop_name, consumption_status);
CREATE INDEX IF NOT EXISTS idx_tppc_task
    ON third_platform_procurement_consumption (task_id);

-- Execution placeholder (stub) for accepted tasks. NOT a real procurement order.
-- execution_status is a new downstream dimension, orthogonal to task/delivery/consumption status.
CREATE TABLE IF NOT EXISTS third_platform_procurement_execution (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                VARCHAR(128)  NOT NULL,
    task_id                  BIGINT        NOT NULL,
    line_id                  VARCHAR(255),
    consumer_id              VARCHAR(128),
    execution_status         VARCHAR(32)   NOT NULL DEFAULT 'PENDING_EXECUTION',
    note                     VARCHAR(512),
    created_at               TIMESTAMP,
    completed_at             TIMESTAMP,
    del_flag                 INT           NOT NULL DEFAULT 0,
    updated_at               TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_tppe_task
    ON third_platform_procurement_execution (task_id);
CREATE INDEX IF NOT EXISTS idx_tppe_shop_status
    ON third_platform_procurement_execution (shop_name, execution_status);

-- Per-shop pricing template (single active row per shop). Deterministic sale-price rule for
-- catalog recommendations: converted = price * exchange_rate; sale = converted * multiplier + addend,
-- then rounding_strategy(decimals). exchange_rate = target units per 1 source unit. Manual/static
-- rate in this phase (no live FX). Template params only; money math is done in BigDecimal in the app.
CREATE TABLE IF NOT EXISTS pricing_template (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                VARCHAR(255)  NOT NULL,
    source_currency          VARCHAR(8)    NOT NULL DEFAULT 'CNY',
    target_currency          VARCHAR(8)    NOT NULL DEFAULT 'USD',
    exchange_rate            DOUBLE PRECISION NOT NULL,
    multiplier               DOUBLE PRECISION NOT NULL DEFAULT 2.0,
    addend                   DOUBLE PRECISION NOT NULL DEFAULT 0,
    rounding_strategy        VARCHAR(16)   NOT NULL DEFAULT 'HALF_UP',
    decimals                 INT           NOT NULL DEFAULT 2,
    del_flag                 INT           NOT NULL DEFAULT 0,
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_pricing_template_shop
    ON pricing_template (shop_name, del_flag);

-- Publish idempotency ledger: one Shopify product per (shop_name, candidate_id). Records the
-- publish lifecycle (PENDING/PUBLISHING/PUBLISHED/FAILED) plus a snapshot of what was published and
-- the Shopify GIDs returned on success. No real Shopify write happens in M1-3; this is the base for
-- M1-4. Money snapshot columns are DECIMAL; template params live in pricing_template.
CREATE TABLE IF NOT EXISTS product_publish_record (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                   VARCHAR(128)  NOT NULL,
    shop_type                   VARCHAR(32)   NOT NULL DEFAULT 'SHOPIFY',
    candidate_id                VARCHAR(255)  NOT NULL,
    tangbuy_product_id          VARCHAR(128),
    offer_id_1688               VARCHAR(128),
    sku_id                      VARCHAR(128),
    title                       VARCHAR(1024),
    source_price                DECIMAL(18, 4),
    source_currency             VARCHAR(16),
    sale_price                  DECIMAL(18, 4),
    target_currency             VARCHAR(16),
    publish_status              VARCHAR(32)   NOT NULL DEFAULT 'PENDING',
    shopify_product_id          VARCHAR(255),
    shopify_product_handle      VARCHAR(255),
    shopify_variant_id          VARCHAR(255),
    shopify_inventory_item_id   VARCHAR(255),
    attempts                    INT           NOT NULL DEFAULT 0,
    error_message               VARCHAR(1024),
    published_at                TIMESTAMP,
    del_flag                    INT           NOT NULL DEFAULT 0,
    created_at                  TIMESTAMP,
    updated_at                  TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ppr_shop_candidate
    ON product_publish_record (shop_name, candidate_id, del_flag);
CREATE INDEX IF NOT EXISTS idx_ppr_shop_status
    ON product_publish_record (shop_name, publish_status);

-- Shop-level logistics strategy template (Phase 1). One active row per shop. markets_json stores
-- [{marketGroupId, countryCodes:["US",...]}, ...]. Lane matching is Phase 2.
CREATE TABLE IF NOT EXISTS logistics_template (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                VARCHAR(255)  NOT NULL,
    packaging                VARCHAR(32)   NOT NULL DEFAULT 'MINIMAL',
    speed_preference         VARCHAR(32)   NOT NULL DEFAULT 'BALANCED',
    markets_json             TEXT          NOT NULL,
    del_flag                 INT           NOT NULL DEFAULT 0,
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_logistics_template_shop
    ON logistics_template (shop_name, del_flag);

-- Per-product logistics type classification for a shop (rule/keyword/user). Used as Phase 2 match input.
CREATE TABLE IF NOT EXISTS product_logistics_profile (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                VARCHAR(255)  NOT NULL,
    third_platform_item_id   VARCHAR(255)  NOT NULL,
    title_snapshot           VARCHAR(1024),
    logistics_type           VARCHAR(32)   NOT NULL,
    confidence               DOUBLE PRECISION NOT NULL DEFAULT 0,
    signals_json             TEXT,
    classify_source          VARCHAR(16)   NOT NULL DEFAULT 'RULE',
    reviewed                 INT           NOT NULL DEFAULT 0,
    del_flag                 INT           NOT NULL DEFAULT 0,
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_plp_shop_item
    ON product_logistics_profile (shop_name, third_platform_item_id, del_flag);
CREATE INDEX IF NOT EXISTS idx_plp_shop_type
    ON product_logistics_profile (shop_name, logistics_type);

-- Background image-auto-match queue (post-auth / manual start). One RUNNING job per shop at a time.
CREATE TABLE IF NOT EXISTS shop_match_job (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name         VARCHAR(128)  NOT NULL,
    job_type          VARCHAR(32)   NOT NULL DEFAULT 'IMAGE_AUTO_MATCH',
    status            VARCHAR(32)   NOT NULL DEFAULT 'PENDING',
    scope_item_id     VARCHAR(255),
    scope_item_ids_json TEXT,
    total_count       INT           NOT NULL DEFAULT 0,
    processed_count   INT           NOT NULL DEFAULT 0,
    linked_count      INT           NOT NULL DEFAULT 0,
    skipped_count     INT           NOT NULL DEFAULT 0,
    failed_count      INT           NOT NULL DEFAULT 0,
    last_error        VARCHAR(1024),
    recent_json       TEXT,
    started_at        TIMESTAMP,
    finished_at       TIMESTAMP,
    created_at        TIMESTAMP,
    updated_at        TIMESTAMP,
    del_flag          INT           NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_smj_shop_status
    ON shop_match_job (shop_name, status);

ALTER TABLE shop_match_job ADD COLUMN IF NOT EXISTS scope_item_ids_json TEXT;

-- ---------------------------------------------------------------------------
-- SKU Align V1: product-level source summary, variant binding, review, runs, knowledge
-- Naming: shop_name = shop_id; third_platform_* = shopify_*; tangbuy_* = offer_*
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS product_source_binding (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                    VARCHAR(128)  NOT NULL,
    third_platform_item_id       VARCHAR(255)  NOT NULL,
    primary_offer_id             VARCHAR(128)  NOT NULL,
    primary_source_type          VARCHAR(32)   NOT NULL,
    status                       VARCHAR(32)   NOT NULL DEFAULT 'ACTIVE',
    supplemental_offer_ids_json  TEXT,
    product_origin               VARCHAR(32)   NOT NULL DEFAULT 'EXTERNAL',
    matched_variants_count       INT           NOT NULL DEFAULT 0,
    total_variants_count         INT           NOT NULL DEFAULT 0,
    unresolved_variants_count    INT           NOT NULL DEFAULT 0,
    last_alignment_run_id        BIGINT,
    last_aligned_at              TIMESTAMP,
    del_flag                     INT           NOT NULL DEFAULT 0,
    created_at                   TIMESTAMP,
    updated_at                   TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_psb_shop_item
    ON product_source_binding (shop_name, third_platform_item_id, del_flag);

CREATE TABLE IF NOT EXISTS variant_sku_binding (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                VARCHAR(128)  NOT NULL,
    third_platform_item_id   VARCHAR(255)  NOT NULL,
    third_platform_sku_id    VARCHAR(255)  NOT NULL,
    offer_id                 VARCHAR(128),
    offer_sku_id             VARCHAR(128),
    source_role              VARCHAR(32)   NOT NULL DEFAULT 'PRIMARY',
    match_source             VARCHAR(32)   NOT NULL,
    binding_state            VARCHAR(32)   NOT NULL,
    confidence_score         DECIMAL(6, 4),
    confidence_level         VARCHAR(16),
    explanation_json         TEXT,
    is_manual_locked         INT           NOT NULL DEFAULT 0,
    active                   INT           NOT NULL DEFAULT 1,
    created_by_type          VARCHAR(16)   NOT NULL DEFAULT 'SYSTEM',
    created_by_id            VARCHAR(128),
    del_flag                 INT           NOT NULL DEFAULT 0,
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_vsb_shop_item_active
    ON variant_sku_binding (shop_name, third_platform_item_id, active, del_flag);
CREATE INDEX IF NOT EXISTS idx_vsb_shop_variant
    ON variant_sku_binding (shop_name, third_platform_sku_id, active, del_flag);

CREATE TABLE IF NOT EXISTS variant_alignment_review (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name                   VARCHAR(128)  NOT NULL,
    third_platform_item_id      VARCHAR(255)  NOT NULL,
    third_platform_sku_id       VARCHAR(255)  NOT NULL,
    current_offer_scope_json    TEXT,
    review_state                VARCHAR(32)   NOT NULL,
    suggested_offer_id          VARCHAR(128),
    suggested_offer_sku_id      VARCHAR(128),
    suggested_source_role       VARCHAR(32),
    suggested_match_source      VARCHAR(32),
    score                       DECIMAL(6, 4),
    confidence_level            VARCHAR(16),
    reason_code                 VARCHAR(64),
    reason_text                 VARCHAR(1024),
    requires_user_action        INT           NOT NULL DEFAULT 0,
    last_run_id                 BIGINT,
    del_flag                    INT           NOT NULL DEFAULT 0,
    created_at                  TIMESTAMP,
    updated_at                  TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_var_shop_variant
    ON variant_alignment_review (shop_name, third_platform_sku_id, del_flag);

CREATE TABLE IF NOT EXISTS alignment_run (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name           VARCHAR(128)  NOT NULL,
    trigger_type        VARCHAR(64)   NOT NULL,
    scope_type          VARCHAR(32)   NOT NULL,
    scope_ids_json      TEXT          NOT NULL,
    engine_version      VARCHAR(32)   NOT NULL DEFAULT 'rule-v1',
    run_status          VARCHAR(32)   NOT NULL DEFAULT 'QUEUED',
    matched_count       INT           NOT NULL DEFAULT 0,
    suggested_count     INT           NOT NULL DEFAULT 0,
    unmapped_count      INT           NOT NULL DEFAULT 0,
    no_source_count     INT           NOT NULL DEFAULT 0,
    blocked_count       INT           NOT NULL DEFAULT 0,
    failed_count        INT           NOT NULL DEFAULT 0,
    started_at          TIMESTAMP,
    finished_at         TIMESTAMP,
    error_summary       VARCHAR(1024),
    del_flag            INT           NOT NULL DEFAULT 0,
    created_at          TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ar_shop_status
    ON alignment_run (shop_name, run_status, created_at);

CREATE TABLE IF NOT EXISTS alignment_candidate (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                   BIGINT        NOT NULL,
    third_platform_sku_id    VARCHAR(255)  NOT NULL,
    rank_no                  INT           NOT NULL,
    offer_id                 VARCHAR(128)  NOT NULL,
    offer_sku_id             VARCHAR(128)  NOT NULL,
    source_role              VARCHAR(32)   NOT NULL DEFAULT 'PRIMARY',
    candidate_source         VARCHAR(32)   NOT NULL,
    score                    DECIMAL(6, 4),
    confidence_level         VARCHAR(16),
    matched_tokens_json      TEXT,
    reason_text              VARCHAR(1024),
    selected_by_system       INT           NOT NULL DEFAULT 0,
    selected_by_user         INT           NOT NULL DEFAULT 0,
    created_at               TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ac_run_variant
    ON alignment_candidate (run_id, third_platform_sku_id);

CREATE TABLE IF NOT EXISTS shop_sku_alias_knowledge (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name        VARCHAR(128)  NOT NULL,
    knowledge_type   VARCHAR(32)   NOT NULL,
    source_text      VARCHAR(512)  NOT NULL,
    target_text      VARCHAR(512)  NOT NULL,
    category_hint    VARCHAR(256),
    offer_id         VARCHAR(128),
    weight           DECIMAL(8, 4) NOT NULL DEFAULT 1.0,
    status           VARCHAR(16)   NOT NULL DEFAULT 'ACTIVE',
    derived_from     VARCHAR(32)   NOT NULL,
    evidence_count   INT           NOT NULL DEFAULT 1,
    last_used_at     TIMESTAMP,
    del_flag         INT           NOT NULL DEFAULT 0,
    created_at       TIMESTAMP,
    updated_at       TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ssak_shop_type
    ON shop_sku_alias_knowledge (shop_name, knowledge_type, status);

